// <auto-generated />
namespace KeepCalmAndMIC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class re_init_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(re_init_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201704300911384_re_init_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
